"""initial

Revision ID: 0.0.0.0
Revises: 
Create Date: 2024-03-20 09:52:51.819170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0.0.0.0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_id'), 'todo', ['id'], unique=False)
    op.create_index(op.f('ix_todo_title'), 'todo', ['title'], unique=False)
        op.execute(
        """
        INSERT INTO tasks (id, task) VALUES
        ('1', 'DarkThemeDflt'),
        ('2', 'OnlyOneSuperuser')
        """
    )
    op.execute(
        """
        INSERT INTO todo (id, title, description) VALUES
        ('4', 'HeaderText', 'description of HeaderText'),
        ('5', 'FooterText', 'description of FooterText')
        """
    )    

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_title'), table_name='todo')
    op.drop_index(op.f('ix_todo_id'), table_name='todo')
    op.drop_table('todo')
    op.drop_table('tasks')
    # ### end Alembic commands ###
